# Generated by Django 5.2 on 2025-05-09 23:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0002_alter_products_quantity_and_more'),
        ('clients', '0004_address_remove_client_state_remove_client_street_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Successful'), ('failed', 'Failed')], default='pending', help_text='Status Choices', max_length=15)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Order Total', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_address', models.ForeignKey(help_text='Billing Adress', on_delete=django.db.models.deletion.DO_NOTHING, related_name='billed_orders', to='clients.address')),
                ('client', models.ForeignKey(help_text='Select the Client making the Order', on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('shipping_address', models.ForeignKey(help_text='Shipping Adress', on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipped_orders', to='clients.address')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Enter OrderItem Quantity', validators=[django.core.validators.MinValueValidator(1)])),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_items', to='Products.products')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_line', to='Orders.orders')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
