# Generated by Django 5.2 on 2025-05-10 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
        ('clients', '0006_client_house_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='billing_address',
            field=models.ForeignKey(help_text='Billing Adress', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billed_orders', to='clients.address'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipping_address',
            field=models.ForeignKey(help_text='Shipping Adress', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipped_orders', to='clients.address'),
        ),
    ]
