# Generated by Django 5.2 on 2025-05-10 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_rename_orders_orderitem_order_and_more'),
        ('Products', '0002_alter_products_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='Products.products'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='client',
            field=models.ForeignKey(help_text='Select the Client making the Order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
