# Generated by Django 5.2 on 2025-05-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_created_at_client_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
