# Generated by Django 5.2 on 2025-05-09 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_address_remove_client_state_remove_client_street_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='house_address',
        ),
    ]
