# Generated by Django 5.2 on 2025-05-09 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_client_house_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='house_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='client', to='clients.address'),
            preserve_default=False,
        ),
    ]
