# Generated by Django 5.2 on 2025-05-10 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_house_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
    ]
