# Generated by Django 5.2 on 2025-05-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Product Name', max_length=255, unique=True)),
                ('quantity', models.IntegerField(help_text='Enter Product Quantity')),
                ('description', models.TextField(help_text='Enter Product Description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter Product Price', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Enter Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Enter Date Updated')),
                ('is_available', models.BooleanField(default=True, help_text='Is Product Available')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
