# Generated by Django 5.2 on 2025-05-09 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(help_text='Enter Product Quantity', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='products',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='quantity_greater_than_zero'),
        ),
    ]
